<a href="https://colab.research.google.com/github/MaxBusha/MaxBusha/blob/main/Machine_Learning_in_Python_Lab_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [46]:
import pandas as pd
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
import io
import warnings
warnings.filterwarnings("ignore")

#reading in of stroke/health dataset
url = 'https://raw.githubusercontent.com/MaxBusha/CS-5324/main/healthcare-dataset-stroke-data.csv?token=GHSAT0AAAAAACNBRTSA5H2H4UA5BBYKRBUSZOD4FCA'
df = pd.read_csv(url)

#usage of replace/inplace function to change categorical, mostly binary, data into integer values
#replace married information to 0 for 'No' and 1 for 'Yes'
df.ever_married.replace(to_replace = ['No', 'Yes'],
                 value = range(0,2), inplace = True)

#replace residence type to 0 for 'rural' and 1 for 'urban'
df.Residence_type.replace(to_replace = ['Rural', 'Urban'],
                 value = range(0,2), inplace = True)

#replace gender info  to 0 for 'male' and 1 for 'female'
df.gender.replace(to_replace = ['Male', 'Female'],
                 value = range(0,2), inplace = True)

#replace smoking info  to 0 for 'never smoked', 1 for 'formerly smoked', and 2 for 'smokes
df.smoking_status.replace(to_replace = ['never smoked', 'formerly smoked', 'smokes'],
                 value = range(0,3), inplace = True)

df.tail()

,id,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke
5104,18234,1,80.0,1,0,1,Private,1,83.75,NaN,0,0
5105,44873,1,81.0,0,0,1,Self-employed,1,125.20,40.0,0,0
5106,19723,1,35.0,0,0,1,Self-employed,0,82.99,30.6,0,0
5107,37544,0,51.0,0,0,1,Private,0,166.29,25.6,1,0
5108,44679,1,44.0,0,0,1,Govt_job,1,85.28,26.2,Unknown,0

In [41]:
# find the data type
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5109 entries, 0 to 5108
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 5109 non-null   int64
 1   gender             5109 non-null   int64
 2   age                5109 non-null   float64
 3   hypertension       5109 non-null   int64
 4   heart_disease      5109 non-null   int64
 5   ever_married       5109 non-null   int64
 6   work_type          5109 non-null   object
 7   Residence_type     5109 non-null   int64
 8   avg_glucose_level  5109 non-null   float64
 9   bmi                4908 non-null   float64
 10  smoking_status     5109 non-null   object
 11  stroke             5109 non-null   int64
dtypes: float64(3), int64(7), object(2)
memory usage: 479.1+ KB
None

This df.info() print shows that we are missing some data under the bmi feature, we will be using the KNN, K-nearest neighbor imputation method to solve this issue.

In [51]:
# impute based upon the K closest samples (rows)
# our first introduction to sklearn!!!
from sklearn.impute import KNNImputer
import copy

# get object for imputation
knn_obj = KNNImputer(n_neighbors=3)

features_to_use = ['gender', 'age', 'hypertension', 'heart_disease', 'ever_married', 'Residence_type', 'avg_glucose_level', 'bmi']

# create a numpy matrix from pandas numeric values to impute
temp = df[features_to_use].to_numpy()

# use sklearn imputation object
knn_obj.fit(temp) # fit the object
temp_imputed = knn_obj.transform(temp) # transform all mssing data
#    could have also done:
# temp_imputed = knn_obj.fit_transform(temp)

# this is VERY IMPORTANT, make a deep copy, not just a reference to the object
# otherwise both data frames will be manipulated
df_imputed = copy.deepcopy(df) # not just an alias
df_imputed[features_to_use] = temp_imputed
df_imputed.dropna(inplace=True)
df_imputed.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5109 entries, 0 to 5108
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 5109 non-null   int64
 1   gender             5109 non-null   float64
 2   age                5109 non-null   float64
 3   hypertension       5109 non-null   float64
 4   heart_disease      5109 non-null   float64
 5   ever_married       5109 non-null   float64
 6   work_type          5109 non-null   object
 7   Residence_type     5109 non-null   float64
 8   avg_glucose_level  5109 non-null   float64
 9   bmi                5109 non-null   float64
 10  smoking_status     5109 non-null   object
 11  stroke             5109 non-null   int64
dtypes: float64(8), int64(2), object(2)
memory usage: 479.1+ KB

The previous info() print shows that we have solved our previous issue with missing values.
Becuase of this we will be setting our dataframe equal to the imputed data so that we can utilize the benefits moving forward.

In [55]:
#setting them equal and using a .info() print to confirm changes
df = df_imputed
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5109 entries, 0 to 5108
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 5109 non-null   int64
 1   gender             5109 non-null   float64
 2   age                5109 non-null   float64
 3   hypertension       5109 non-null   float64
 4   heart_disease      5109 non-null   float64
 5   ever_married       5109 non-null   float64
 6   work_type          5109 non-null   object
 7   Residence_type     5109 non-null   float64
 8   avg_glucose_level  5109 non-null   float64
 9   bmi                5109 non-null   float64
 10  smoking_status     5109 non-null   object
 11  stroke             5109 non-null   int64
dtypes: float64(8), int64(2), object(2)
memory usage: 479.1+ KB
None

In [54]:
# properties of the imputer after fitting
print(knn_obj.n_features_in_)

8
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5109 entries, 0 to 5108
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 5109 non-null   int64
 1   gender             5109 non-null   int64
 2   age                5109 non-null   float64
 3   hypertension       5109 non-null   int64
 4   heart_disease      5109 non-null   int64
 5   ever_married       5109 non-null   int64
 6   work_type          5109 non-null   object
 7   Residence_type     5109 non-null   int64
 8   avg_glucose_level  5109 non-null   float64
 9   bmi                4908 non-null   float64
 10  smoking_status     5109 non-null   object
 11  stroke             5109 non-null   int64
dtypes: float64(3), int64(7), object(2)
memory usage: 479.1+ KB
None

In [56]:
df.describe()

,id,gender,age,hypertension,heart_disease,ever_married,Residence_type,avg_glucose_level,bmi,stroke
count,5109.000000,5109.000000,5109.000000,5109.000000,5109.000000,5109.000000,5109.000000,5109.000000,5109.000000,5109.000000
mean,36513.985516,0.586025,43.229986,0.097475,0.054022,0.656293,0.508123,106.140399,28.932531,0.048738
std,21162.008804,0.492592,22.613575,0.296633,0.226084,0.474991,0.499983,45.285004,7.780808,0.215340
min,67.000000,0.000000,0.080000,0.000000,0.000000,0.000000,0.000000,55.120000,10.300000,0.000000
25%,17740.000000,0.000000,25.000000,0.000000,0.000000,0.000000,0.000000,77.240000,23.700000,0.000000
50%,36922.000000,1.000000,45.000000,0.000000,0.000000,1.000000,1.000000,91.880000,28.200000,0.000000
75%,54643.000000,1.000000,61.000000,0.000000,0.000000,1.000000,1.000000,114.090000,33.100000,0.000000
max,72940.000000,1.000000,82.000000,1.000000,1.000000,1.000000,1.000000,271.740000,97.600000,1.000000